language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - develop
install:
  - npm install -g firebase-tools
  - npm install -g typescript
  - cd functions
  - npm install
  - tsc
  - cd ..
script:
  - firebase use default --token $FIREBASE_DEPLOY_KEY
  - firebase functions:config:set cron.apiKey=$CRON_API_KEY --token $FIREBASE_DEPLOY_KEY
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER" --non-interactive --token $FIREBASE_DEPLOY_KEY
